### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by Xwang1976** [bartoszek/AUR-scilab-git#1]
Today I get the following error while building the package:

<pre><code>
File "./src/modelica_compiler/scicosOptimizingCompiler.ml", line 1:
Error: Files /usr/lib/ocaml/num/nums.cmxa and /usr/lib/ocaml/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__sys
Command exited with non-zero status 2
</code></pre>

Should I open a bug upstream? Is it an ocaml arch packaging issue?

**Comment by Xwang1976** [comment]
Reverting to the previous version of ocaml packages solves the issue

**Comment by atlantasticMKQ** [comment]
I get this error as well
```
File "./src/modelica_compiler/scicosOptimizingCompiler.ml", line 1:
Error: Files /usr/lib/ocaml/num/nums.cmxa and /usr/lib/ocaml/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__sys
Command exited with non-zero status 2
2.59user 0.24system 0:03.34elapsed 84%CPU (0avgtext+0avgdata 44376maxresident)k
29280inputs+3512outputs (11major+47651minor)pagefaults 0swaps
```

**Comment by TheEstMac** [comment]
> Reverting to the previous version of ocaml packages solves the issue

What version did you go back to?

**Comment by Xwang1976** [comment]
The working one is the 4.10.0-1.
The one which does not work is the 4.11.1-1.

I'm using arch linux 64 bit.

**Comment by bartoszek** [comment]
Reported on [Arch bug tracker.](https://bugs.archlinux.org/task/68948?project=5&string=ocaml-num)
